apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: g-server
  template:
    metadata:
      labels:
        app: g-server
    spec:
      containers:
      - name: server
        image: nginx
