apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: complex-pod
  name: complex-pod
spec:
  containers:
    - image: nginx
      name: complex-pod
      ports:
        - containerPort: 80
      resources: { }
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  initContainers:
    - name: initializer
      image: busybox
      command: [ '/bin/sh', '-c', 'wget -O- google.com' ]
status: { }
