apiVersion: v1
kind: Pod
metadata:
  name: data-exchange
spec:
  containers:
  - image: busybox
    name: main-app
    command: ['sh']
    args: ['-c', 'counter=1; while true; do touch "/var/app/data/$counter-data.txt"; counter=$((counter+1)); sleep 2; done']
    resources: {}
    volumeMounts:
      - name: shared
        mountPath: /var/app/data
  
  - image: busybox
    name: sidecar
    command: ['sh']
    args: ['-c', 'while true; do ls -1 /var/app/data | wc -l; sleep 4; done;']
    volumeMounts:
      - name: shared
        mountPath: /var/app/data
  
  volumes:
  - name: shared
    emptyDir: {}

  dnsPolicy: ClusterFirst
  restartPolicy: Never

status: {}