apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: data-exchange
  name: data-exchange
spec:
  containers:
  - image: busybox
    name: main-app
    resources: {}
    command: ['/bin/sh']
    args: 
      - '-c'
      - mkdir -p /var/app/data
      - 'I=1'
      - 'while true; do'
      - touch /var/app/data/$I-data.txt
      - sleep 5
      - I=$((I+1))
      - done
  - name: sidecar
    image: busybox
    command: 
      - /bin/sh
    args:
      - -c
      - >
        while true; do
          ls /var/app/data
          sleep 10
        done
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
