apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpines
  name: alpines
spec:
  containers:
    - image: alpine:3.12.0
      name: alpinei-a
      volumeMounts:
        - name: shared
          mountPath: /etc/a
      command: [ '/bin/sh' ]
      args: [ '-c', 'while true; do sleep 60; done;' ]
    - image: alpine:3.12.0
      name: alpine-b
      volumeMounts:
        - name: shared
          mountPath: /etc/b
      command: [ '/bin/sh' ]
      args: [ '-c', 'while true; do sleep 60; done;' ]
  dnsPolicy: ClusterFirst
  restartPolicy: Never

  volumes:
    - name: shared
      emptyDir: { }
