apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-1
  version: '1.27'
nodeGroups:
  - name: ng-1
    instanceType: m5.medium
    desiredCapacity: 2
    availabilityZones: [ "eu-west-1a", "eu-west-1b" ]