apiVersion: batch/v1
kind: Job
metadata:
  name: sleepy
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sleep"]
        args: ["3"]
      restartPolicy: Never
  completions: 5
  parallelism: 2
  activeDeadlineSeconds: 15
