apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: addons-test
  region: ap-northeast-2
  version: '1.27'
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    availabilityZones: [ "eu-west-1a", "eu-west-1b" ]