apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: pvc-consumer
spec:
  volumes:
    - name: nginx-logs
      persistentVolumeClaim:
        claimName: logs-pvc
  containers:
  - image: nginx
    name: pvc-consumer
    volumeMounts:
      - mountPath: /var/log/nginx
        name: nginx-logs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
