apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: custom-cmd
  name: custom-cmd
spec:
  containers:
    - image: busybox
      name: custom-cmd
      resources: { }
      command: [ '/bin/sh' ]
      args: [ '-c', 'top-analyzer', '--all' ]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: { }
