apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-server
  name: web-server
spec:
  containers:
  - image: nginx
    name: web-server
    ports:
    - containerPort: 80
      name: web
    resources: {}
    readinessProbe:
      httpGet:
        path: /
        port: web
      initialDelaySeconds: 5
    startupProbe:
      httpGet:
        path: /
        port: web
    livenessProbe:
      httpGet:
        path: /
        port: web
      periodSeconds: 30
      initialDelaySeconds: 10
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
