apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  containers:
  - image: alpine
    name: alpine
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
  restartPolicy: Never
