apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: security-context-demo-book
  name: security-context-demo-book
spec:
  containers:
  - image: alpine
    name: security-context-demo
    resources: {}
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
  dnsPolicy: ClusterFirst
    #  restartPolicy: Never
status: {}
